version: '3.1'

services:

  db:
    container_name: database
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ".env"
    network_mode: "host"

  tgbot:
    container_name: bot
    build: .
    volumes:
      - .:/src
    command: sh -c "ln -snf /usr/share/zoneinfo/Europe/Moscow /etc/localtime && echo Europe/Moscow > /etc/timezone && python app.py"
    restart: always
    network_mode: "host"
    env_file:
      - ".env"
